require "spec"
require "../src/findata-avan"
require "../src/findata-avan/time-series/*"
require "../src/findata-avan/quote/*"
require "../src/findata-avan/search/*"
require "dotenv"
Dotenv.load ".env"
